language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get -y install qt59-meta-full

script:
  - source /opt/qt59/bin/qt59-env.sh
  - /opt/qt59/bin/qmake -config release mjpancake.pro
  - make

